api:
  build: ./api
  ports:
    - 3000:3000
  volumes:
    - ./api:/go/src/github.com/mehrat/train-app/api
  links:
    - database
  environment:
    - DB_NAME=trainDB

database:
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null